// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALvBj7iagv22vFQDbG-17FLo4D1YzsBtM',
    appId: '1:374672195536:web:855bac70de424219c003d5',
    messagingSenderId: '374672195536',
    projectId: 'roamify-e9e8f',
    authDomain: 'roamify-e9e8f.firebaseapp.com',
    storageBucket: 'roamify-e9e8f.appspot.com',
    measurementId: 'G-X1S0L8WS99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kukB55diZYSlY72Y2JoshBtJToahmUs',
    appId: '1:374672195536:android:e92b03eae5e3890dc003d5',
    messagingSenderId: '374672195536',
    projectId: 'roamify-e9e8f',
    storageBucket: 'roamify-e9e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9ZzIxoUrcnQkXU7zsCOcITQIAtuP2Og',
    appId: '1:374672195536:ios:d7397438ce764606c003d5',
    messagingSenderId: '374672195536',
    projectId: 'roamify-e9e8f',
    storageBucket: 'roamify-e9e8f.appspot.com',
    androidClientId: '374672195536-tana2uk1t40lm4mjtd1n04o9ae43dlmr.apps.googleusercontent.com',
    iosClientId: '374672195536-kh3pubdetm26oh8nh8f4cedr0cflvm3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSetup',
  );
}
